# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5fa03f187fc0bd25fb8814e3a22e103a7d2c5cc590e2e053b2d8e6aac3e8388f9e9363cc2d92b4f2e7677f17b0aa8dc29da16fb7d5d9595363017532adebd756

test:
  secret_key_base: 1cc6cf6aa3d904d85a69b63f062bb1763f3749cb39f412a3fb6342d356a74a17ec179c3152c6dfc147fe940cd9e779c5ae9e67c0a7d5c88dc5bb95132af6c197

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
